# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36c86702bc7aee028b9ed16320cdec82254ed92de0188d0c3ca4f9512e1f7d683e26a02a1bcb87f5f0df9c96ace83dd4b485789e1d599366466bb3a999731276

test:
  secret_key_base: 7716286c9ff8d815ec4272d128b658fd04f95a0795c8d87cfc6e7a4d5efa2cfaccc1ef6de544ccfbbfd56947d98b10fffb09185394fa6b500d82d440cfaffe60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
